import type { ChainId } from "@/types";
import {
  ARC_CHAIN_ID,
  ARC_EXPLORER,
  ARC_NETWORK_NAME,
  ARC_TESTNET_RPC,
  ARC_CURRENCY_DECIMALS,
  ARC_CURRENCY_NAME,
  ARC_CURRENCY_SYMBOL,
} from "@/lib/arc-chain";

export interface ChainMeta {
  id: ChainId;
  label: string;
  short: string;
  color: string;
  explorer: string;
  appKitName: string;
  testnet: boolean;
}

export const CHAINS: Record<ChainId, ChainMeta> = {
  Arbitrum: {
    id: "Arbitrum",
    label: "Arbitrum",
    short: "Arbi",
    color: "#a3a3a3",
    explorer: "https://explorer.arbitrum.com",
    appKitName: "Arbitrum",
    testnet: false,
  },
  Avalanche: {
    id: "Avalanche",
    label: "Avalanche",
    short: "Aval",
    color: "#a3a3a3",
    explorer: "https://explorer.avalanche.com",
    appKitName: "Avalanche",
    testnet: false,
  },
  Base: {
    id: "Base",
    label: "Base",
    short: "Base",
    color: "#a3a3a3",
    explorer: "https://explorer.base.com",
    appKitName: "Base",
    testnet: false,
  },
  Codex: {
    id: "Codex",
    label: "Codex",
    short: "Code",
    color: "#a3a3a3",
    explorer: "https://explorer.codex.com",
    appKitName: "Codex",
    testnet: false,
  },
  Cronos: {
    id: "Cronos",
    label: "Cronos",
    short: "Cron",
    color: "#a3a3a3",
    explorer: "https://explorer.cronos.com",
    appKitName: "Cronos",
    testnet: false,
  },
  Edge: {
    id: "Edge",
    label: "Edge",
    short: "Edge",
    color: "#a3a3a3",
    explorer: "https://explorer.edge.com",
    appKitName: "Edge",
    testnet: false,
  },
  Ethereum: {
    id: "Ethereum",
    label: "Ethereum",
    short: "Ethe",
    color: "#a3a3a3",
    explorer: "https://explorer.ethereum.com",
    appKitName: "Ethereum",
    testnet: false,
  },
  HyperEVM: {
    id: "HyperEVM",
    label: "HyperEVM",
    short: "Hype",
    color: "#a3a3a3",
    explorer: "https://explorer.hyperevm.com",
    appKitName: "HyperEVM",
    testnet: false,
  },
  Injective: {
    id: "Injective",
    label: "Injective",
    short: "Inje",
    color: "#a3a3a3",
    explorer: "https://explorer.injective.com",
    appKitName: "Injective",
    testnet: false,
  },
  Ink: {
    id: "Ink",
    label: "Ink",
    short: "Ink",
    color: "#a3a3a3",
    explorer: "https://explorer.ink.com",
    appKitName: "Ink",
    testnet: false,
  },
  Linea: {
    id: "Linea",
    label: "Linea",
    short: "Line",
    color: "#a3a3a3",
    explorer: "https://explorer.linea.com",
    appKitName: "Linea",
    testnet: false,
  },
  Monad: {
    id: "Monad",
    label: "Monad",
    short: "Mona",
    color: "#a3a3a3",
    explorer: "https://explorer.monad.com",
    appKitName: "Monad",
    testnet: false,
  },
  Morph: {
    id: "Morph",
    label: "Morph",
    short: "Morp",
    color: "#a3a3a3",
    explorer: "https://explorer.morph.com",
    appKitName: "Morph",
    testnet: false,
  },
  Optimism: {
    id: "Optimism",
    label: "Optimism",
    short: "Opti",
    color: "#a3a3a3",
    explorer: "https://explorer.optimism.com",
    appKitName: "Optimism",
    testnet: false,
  },
  Pharos: {
    id: "Pharos",
    label: "Pharos",
    short: "Phar",
    color: "#a3a3a3",
    explorer: "https://explorer.pharos.com",
    appKitName: "Pharos",
    testnet: false,
  },
  Plume: {
    id: "Plume",
    label: "Plume",
    short: "Plum",
    color: "#a3a3a3",
    explorer: "https://explorer.plume.com",
    appKitName: "Plume",
    testnet: false,
  },
  Polygon: {
    id: "Polygon",
    label: "Polygon",
    short: "Poly",
    color: "#a3a3a3",
    explorer: "https://explorer.polygon.com",
    appKitName: "Polygon",
    testnet: false,
  },
  Sei: {
    id: "Sei",
    label: "Sei",
    short: "Sei",
    color: "#a3a3a3",
    explorer: "https://explorer.sei.com",
    appKitName: "Sei",
    testnet: false,
  },
  Solana: {
    id: "Solana",
    label: "Solana",
    short: "Sola",
    color: "#a3a3a3",
    explorer: "https://explorer.solana.com",
    appKitName: "Solana",
    testnet: false,
  },
  Sonic: {
    id: "Sonic",
    label: "Sonic",
    short: "Soni",
    color: "#a3a3a3",
    explorer: "https://explorer.sonic.com",
    appKitName: "Sonic",
    testnet: false,
  },
  Unichain: {
    id: "Unichain",
    label: "Unichain",
    short: "Unic",
    color: "#a3a3a3",
    explorer: "https://explorer.unichain.com",
    appKitName: "Unichain",
    testnet: false,
  },
  World_Chain: {
    id: "World_Chain",
    label: "World Chain",
    short: "Worl",
    color: "#a3a3a3",
    explorer: "https://explorer.worldchain.com",
    appKitName: "World_Chain",
    testnet: false,
  },
  XDC: {
    id: "XDC",
    label: "XDC",
    short: "XDC",
    color: "#a3a3a3",
    explorer: "https://explorer.xdc.com",
    appKitName: "XDC",
    testnet: false,
  },
  Arc_Testnet: {
    id: "Arc_Testnet",
    label: "Arc Testnet",
    short: "Arc",
    color: "#22d3ee",
    explorer: "https://testnet.arcscan.app",
    appKitName: "Arc_Testnet",
    testnet: true,
  },
  Arbitrum_Sepolia: {
    id: "Arbitrum_Sepolia",
    label: "Arbitrum Sepolia",
    short: "Arb",
    color: "#28a0f0",
    explorer: "https://sepolia.arbiscan.io",
    appKitName: "Arbitrum_Sepolia",
    testnet: true,
  },
  Avalanche_Fuji: {
    id: "Avalanche_Fuji",
    label: "Avalanche Fuji",
    short: "Avax",
    color: "#e84142",
    explorer: "https://testnet.snowtrace.io",
    appKitName: "Avalanche_Fuji",
    testnet: true,
  },
  Base_Sepolia: {
    id: "Base_Sepolia",
    label: "Base Sepolia",
    short: "Base",
    color: "#0052ff",
    explorer: "https://sepolia.basescan.org",
    appKitName: "Base_Sepolia",
    testnet: true,
  },
  Codex_Testnet: {
    id: "Codex_Testnet",
    label: "Codex Testnet",
    short: "Code",
    color: "#a3a3a3",
    explorer: "https://explorer.codextestnet.com",
    appKitName: "Codex_Testnet",
    testnet: true,
  },
  Cronos_Testnet: {
    id: "Cronos_Testnet",
    label: "Cronos Testnet",
    short: "Cron",
    color: "#a3a3a3",
    explorer: "https://explorer.cronostestnet.com",
    appKitName: "Cronos_Testnet",
    testnet: true,
  },
  Edge_Testnet: {
    id: "Edge_Testnet",
    label: "Edge Testnet",
    short: "Edge",
    color: "#a3a3a3",
    explorer: "https://explorer.edgetestnet.com",
    appKitName: "Edge_Testnet",
    testnet: true,
  },
  Ethereum_Sepolia: {
    id: "Ethereum_Sepolia",
    label: "Ethereum Sepolia",
    short: "ETH",
    color: "#627eea",
    explorer: "https://sepolia.etherscan.io",
    appKitName: "Ethereum_Sepolia",
    testnet: true,
  },
  HyperEVM_Testnet: {
    id: "HyperEVM_Testnet",
    label: "HyperEVM Testnet",
    short: "Hype",
    color: "#a3a3a3",
    explorer: "https://explorer.hyperevmtestnet.com",
    appKitName: "HyperEVM_Testnet",
    testnet: true,
  },
  Injective_Testnet: {
    id: "Injective_Testnet",
    label: "Injective Testnet",
    short: "Inje",
    color: "#a3a3a3",
    explorer: "https://explorer.injectivetestnet.com",
    appKitName: "Injective_Testnet",
    testnet: true,
  },
  Ink_Testnet: {
    id: "Ink_Testnet",
    label: "Ink Testnet",
    short: "Ink_",
    color: "#a3a3a3",
    explorer: "https://explorer.inktestnet.com",
    appKitName: "Ink_Testnet",
    testnet: true,
  },
  Linea_Sepolia: {
    id: "Linea_Sepolia",
    label: "Linea Sepolia",
    short: "Line",
    color: "#a3a3a3",
    explorer: "https://explorer.lineasepolia.com",
    appKitName: "Linea_Sepolia",
    testnet: true,
  },
  Monad_Testnet: {
    id: "Monad_Testnet",
    label: "Monad Testnet",
    short: "Mona",
    color: "#a3a3a3",
    explorer: "https://explorer.monadtestnet.com",
    appKitName: "Monad_Testnet",
    testnet: true,
  },
  Morph_Testnet: {
    id: "Morph_Testnet",
    label: "Morph Testnet",
    short: "Morp",
    color: "#a3a3a3",
    explorer: "https://explorer.morphtestnet.com",
    appKitName: "Morph_Testnet",
    testnet: true,
  },
  Optimism_Sepolia: {
    id: "Optimism_Sepolia",
    label: "Optimism Sepolia",
    short: "OP",
    color: "#ff0420",
    explorer: "https://sepolia-optimism.etherscan.io",
    appKitName: "Optimism_Sepolia",
    testnet: true,
  },
  Pharos_Testnet: {
    id: "Pharos_Testnet",
    label: "Pharos Testnet",
    short: "Phar",
    color: "#a3a3a3",
    explorer: "https://explorer.pharostestnet.com",
    appKitName: "Pharos_Testnet",
    testnet: true,
  },
  Plume_Testnet: {
    id: "Plume_Testnet",
    label: "Plume Testnet",
    short: "Plum",
    color: "#a3a3a3",
    explorer: "https://explorer.plumetestnet.com",
    appKitName: "Plume_Testnet",
    testnet: true,
  },
  Polygon_Amoy_Testnet: {
    id: "Polygon_Amoy_Testnet",
    label: "Polygon Amoy",
    short: "Pol",
    color: "#8247e5",
    explorer: "https://amoy.polygonscan.com",
    appKitName: "Polygon_Amoy_Testnet",
    testnet: true,
  },
  Sei_Testnet: {
    id: "Sei_Testnet",
    label: "Sei Testnet",
    short: "Sei_",
    color: "#a3a3a3",
    explorer: "https://explorer.seitestnet.com",
    appKitName: "Sei_Testnet",
    testnet: true,
  },
  Solana_Devnet: {
    id: "Solana_Devnet",
    label: "Solana Devnet",
    short: "Sol",
    color: "#14f195",
    explorer: "https://explorer.solana.com/?cluster=devnet",
    appKitName: "Solana_Devnet",
    testnet: true,
  },
  Sonic_Testnet: {
    id: "Sonic_Testnet",
    label: "Sonic Testnet",
    short: "Soni",
    color: "#a3a3a3",
    explorer: "https://explorer.sonictestnet.com",
    appKitName: "Sonic_Testnet",
    testnet: true,
  },
  Unichain_Sepolia: {
    id: "Unichain_Sepolia",
    label: "Unichain Sepolia",
    short: "Unic",
    color: "#a3a3a3",
    explorer: "https://explorer.unichainsepolia.com",
    appKitName: "Unichain_Sepolia",
    testnet: true,
  },
  World_Chain_Sepolia: {
    id: "World_Chain_Sepolia",
    label: "World Chain Sepolia",
    short: "Worl",
    color: "#a3a3a3",
    explorer: "https://explorer.worldchainsepolia.com",
    appKitName: "World_Chain_Sepolia",
    testnet: true,
  },
  XDC_Apothem: {
    id: "XDC_Apothem",
    label: "XDC Apothem",
    short: "XDC_",
    color: "#a3a3a3",
    explorer: "https://explorer.xdcapothem.com",
    appKitName: "XDC_Apothem",
    testnet: true,
  },
};

export const ARC_TESTNET = {
  id: ARC_CHAIN_ID,
  name: ARC_NETWORK_NAME,
  network: "arc-testnet",
  nativeCurrency: {
    name: ARC_CURRENCY_NAME,
    symbol: ARC_CURRENCY_SYMBOL,
    decimals: ARC_CURRENCY_DECIMALS,
  },
  rpcUrls: {
    default: { http: [ARC_TESTNET_RPC] },
    public: { http: [ARC_TESTNET_RPC] },
  },
  blockExplorers: {
    default: { name: "ArcScan", url: ARC_EXPLORER },
  },
  testnet: true,
} as const;

export const CHAIN_LIST = Object.values(CHAINS);

export function resolveChain(input?: string): ChainId | undefined {
  if (!input) return undefined;
  const q = input.toLowerCase().trim();
  const aliases: Record<string, ChainId> = {
    arc: "Arc_Testnet",
    "arc testnet": "Arc_Testnet",
    eth: "Ethereum_Sepolia",
    ethereum: "Ethereum_Sepolia",
    sepolia: "Ethereum_Sepolia",
    base: "Base_Sepolia",
    arb: "Arbitrum_Sepolia",
    arbitrum: "Arbitrum_Sepolia",
    op: "Optimism_Sepolia",
    optimism: "Optimism_Sepolia",
    polygon: "Polygon_Amoy_Testnet",
    matic: "Polygon_Amoy_Testnet",
    amoy: "Polygon_Amoy_Testnet",
    avax: "Avalanche_Fuji",
    avalanche: "Avalanche_Fuji",
    fuji: "Avalanche_Fuji",
    sol: "Solana_Devnet",
    solana: "Solana_Devnet",
  };
  if (aliases[q]) return aliases[q];
  const hit = CHAIN_LIST.find(
    (c) =>
      c.id.toLowerCase() === q ||
      c.label.toLowerCase() === q ||
      c.short.toLowerCase() === q,
  );
  return hit?.id;
}
